### ISSUE TITLE
Jargon Section: Remove "Dynamic", "Iteration", and "Mutable"

### ISSUE THREAD

**Issue by ROgbonna1** [MostlyFocusedMike/test-app#2]
https://github.com/MostlyFocusedMike/test-app/blob/702a9131ba854fa5ae92a7ad33d632772263fba0/0-getting-started.html#L167

I _love_ introducing them to "jargon" early on. "Syntax", "console", and "debugging" all feel right for lesson one. I'm afraid, however, that "dynamic", "iterations", and "mutable" require too much prior context to understand at this point. Introducing these terms in lesson 0 may cause students to fall down an unproductive rabbit hole. Can we save these terms for future lessons, where they become more relevant?

**Comment by MostlyFocusedMike** [comment]
Agreed let's get them into the lessons as soon as possible.
