### ISSUE TITLE
Clarification: Return vs. Console.log

### ISSUE THREAD

**Issue by ROgbonna1** [MostlyFocusedMike/test-app#4]
https://github.com/MostlyFocusedMike/test-app/blob/702a9131ba854fa5ae92a7ad33d632772263fba0/2-functions.html#L240

This is a "nice-to-have" challenge that we can address when time allows. In your video, you do a great job of defining _return_. While you define it somewhat here, if I'm a beginner, I may be confused about the difference between _returning_ and _logging to the console_. I might be asking, "why would I ever want to return when I can just log?" It may be worth adding a callout section here to address this potential misconception.

**Comment by MostlyFocusedMike** [comment]
Yup, good call out, I added a section specifically talking about why you want to return values vs log them
