### ISSUE TITLE
Feedback: Too Much Information

### ISSUE THREAD

**Issue by ROgbonna1** [MostlyFocusedMike/test-app#5]
https://github.com/MostlyFocusedMike/test-app/blob/702a9131ba854fa5ae92a7ad33d632772263fba0/3-flow-control.html#L160

Control flow is a deep cave with a lot of potential enclaves to explore. It's a hard balance to strike between being thorough and being clear. For this lesson, I want to err on the side of simplicity. By the end of this section, I would like students to be able to write clear `if`-`else` statements and nothing more. You and I know that there are a lot of other important foundational concepts related to control flow; however, I'm okay with us waiting to expose them to these topics until they start their Marcy Lab School journey.

In order to keep this section clear and concise, I propose cutting the following sections:
* **Storing Conditionals** - Naming conventions are not important for them to know right now. It is enough to simply expose them to these conditions by using them in your example problems.
* **Reversing Conditionals** - They don't need these to complete the assignment. If they run across this in their own research, let them fall down the rabbit hole on their own.
* **Truthy and Falsy Values** - This is an important topic but one that takes some time to understand. Exposing them to `true` vs _truthy_ at this stage will likely just lead to more confusion. We have plenty of time for this when they get to Marcy!
* **Reassigning Variables**, **Return vs. Else**, and **Number Ranges** all reinforce good code style but are not important to understand during a student's first exposure to control flow.

I know that removing these sections will make for a much shorter lesson but I truly feel that less is more here.

**Comment by MostlyFocusedMike** [comment]
this makes sense, the _only_ one that we kind of have to keep is reassigning variables (it's required for the code challenge) but I can toss all the rest for now. I am keeping a drastically reduced (no name conventions or codepen and smaller examples) conditional assignment so I don't have to rewrite the problem sets for now, but it's the spirit of what you're after I think.
