### ISSUE TITLE
Remove "Negative Numbers and slice" section

### ISSUE THREAD

**Issue by ROgbonna1** [MostlyFocusedMike/test-app#7]
https://github.com/MostlyFocusedMike/test-app/blob/702a9131ba854fa5ae92a7ad33d632772263fba0/4-strings.html#L285

`slice` is already a lot to wrap your head around as a new developer. Let's not throw negative numbers into the mix. Let's remove this section altogether.

**Comment by MostlyFocusedMike** [comment]
Sure thing
