### ISSUE TITLE
Remove "wrong-ish" convention

### ISSUE THREAD

**Issue by ROgbonna1** [MostlyFocusedMike/test-app#8]
https://github.com/MostlyFocusedMike/test-app/blob/702a9131ba854fa5ae92a7ad33d632772263fba0/4-strings.html#L383

I think I understand why this is "wrong-ish" but I'm not sure a new coder would. Either remove this line or add a sentence or two about why you consider this one a poor option.

**Comment by MostlyFocusedMike** [comment]
Yea i'll just take it out
