### ISSUE TITLE
Question: Do we need Lesson 6?

### ISSUE THREAD

**Issue by ROgbonna1** [MostlyFocusedMike/test-app#9]
https://github.com/MostlyFocusedMike/test-app/blob/702a9131ba854fa5ae92a7ad33d632772263fba0/6-problem-solving.html#L33

Hey Mike!

This lesson on problem-solving is so thoughtfully designed. I love your step-by-step approach to dealing with this problem that would be very difficult for students to contend with otherwise. However, my first thought, after looking at the demo problem and the additional examples, was that these challenges are too hard. They require more problem-solving than I believe is necessary for an admissions task. When I looked ahead to the application questions, I saw that the lesson 6 questions were much harder. 

While the Lesson 6 questions require creative problem-solving (i.e. "how do I get a random letter from a string?"), the application questions simply ask students to apply their knowledge of loops, strings, and conditionals. While Lesson 6 might be great practice for some, I think it will be overwhelming and confidence-breaking for others. What do you think about cutting this section altogether?

**Comment by MostlyFocusedMike** [comment]
Yea we can cut it
